services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    ports:
      - "127.0.0.1:8090:8080"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx768m"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    mem_limit: 1536m

volumes:
  jenkins_home:
